# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.1.4'

gem 'guard'
gem 'guard-rake'
gem 'guard-rubocop'
gem 'minitest'
gem 'rubocop'
gem 'rubocop-minitest'
gem 'rubocop-performance'
