env:
  RUBY_VERSION: 3.1
name: Ruby tests
on: [push,pull_request]
jobs:
    rubocop-test:
      name: Rubocop
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ env.RUBY_VERSION }}
        - name: Install Rubocop
          run: gem install rubocop rubocop-minitest rubocop-performance
          working-directory: ./ruby
        - name: Check code
          run: rubocop
          working-directory: ./ruby
    mini-test:
      name: MiniTest
      needs: rubocop-test
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ env.RUBY_VERSION }}
        - name: Install dependencies
          run: |
            gem install bundler
            bundler install
          working-directory: ./ruby
        - name: Run tests
          run: rake test
          working-directory: ./ruby

  